services:
  db:
    image: postgres:15
    container_name: chat-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    image: node:18-alpine  # Use Node image directly
    container_name: chat-backend
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./backend:/app  # Mount your backend code
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - REDIS_URL=redis://localhost:6380

volumes:
  db-data: